# SCONS build file, will generate and invoke tests.
# 
# ====================================================================
# Copyright (c) 2008 Ian Blumel.  All rights reserved.
# 
# This software is licensed as described in the file LICENSE, which
# you should have received as part of this distribution.  
# ====================================================================
# 
# file: SConscript

import os

# Setup

Repository("tests")
env = Environment(CPPPATH=["..\include"])

# Standard Tests

env.Program("test_basic.c")
env.Program("test_1suite.c")
env.Program("test_count.c")
env.Program("test_kern.c")
env.Program("test_fail.c")
env.Program("test_money.c")
env.Program("test_multi.c")

# Tests involves building a program first. Really we can do this
# via the python WITHIN the SCONS script, but this is also an 
# exercise in learning what we can do with SCONS.

import os
def run_mkbigtest(target=None, source=None, env=None):
   dir_, prgm = os.path.split(target[0].abspath)
   cwd = os.getcwd()
   os.chdir(dir_)
   os.system(prgm)
   os.chdir(cwd)

mkbigtest = env.Program("mkbigtest.c")
env.AddPostAction(mkbigtest, run_mkbigtest)

test_big = env.Program("test_big.c")
Depends(test_big, mkbigtest)
